name: Deploy to Huggingface

on:
  push:
    branches:
      - master  # atau main, sesuaikan dengan nama branch utama Anda

jobs:
  deploy-to-huggingface:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Git
      - name: Setup Git for Huggingface
        run: |
          git config --global user.email "your-email@example.com"  # Ganti dengan email Anda
          git config --global user.name "akii99"  # Ganti dengan username HF Anda

      # Create .gitignore for Hugging Face Space
      - name: Create .gitignore for binary files
        run: |
          mkdir -p temp_space
          echo "# Ignore binary files" > temp_space/.gitignore
          echo "*.jpg" >> temp_space/.gitignore
          echo "*.jpeg" >> temp_space/.gitignore
          echo "*.png" >> temp_space/.gitignore
          echo "*.gif" >> temp_space/.gitignore
          echo "*.webp" >> temp_space/.gitignore
          echo "static/uploads/covers/" >> temp_space/.gitignore

      # Clone Huggingface Space Repository dengan token
      - name: Clone Huggingface Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://$HF_TOKEN@huggingface.co/spaces/akii99/FP-PWEB space

      # Create uploads directory structure
      - name: Create uploads directory structure
        run: |
          mkdir -p space/static/uploads/covers

      # Copy Files to Huggingface Space (Excluding binary files)
      - name: Copy Files to Space
        run: |
          cp temp_space/.gitignore space/
          rsync -av --exclude='.git' --exclude='static/uploads/covers/*.jpg' --exclude='static/uploads/covers/*.jpeg' --exclude='static/uploads/covers/*.png' --exclude='static/uploads/covers/*.webp' --exclude='static/uploads/covers/*.gif' ./ space/

      # Create README for covers directory explaining the exclusion
      - name: Create README for covers directory
        run: |
          echo "# Image Uploads Directory" > space/static/uploads/covers/README.md
          echo "" >> space/static/uploads/covers/README.md
          echo "This directory is used for storing uploaded book cover images." >> space/static/uploads/covers/README.md
          echo "" >> space/static/uploads/covers/README.md
          echo "Note: Actual image files are not included in the repository to comply with Hugging Face's binary file policies." >> space/static/uploads/covers/README.md

      # Commit and Push to Huggingface Space
      - name: Commit and Push to Huggingface
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd space
          git add .
          git commit -m "Deploy files from GitHub repository (excluding binary files)" || echo "No changes to commit"
          git push https://$HF_TOKEN@huggingface.co/spaces/akii99/FP-PWEB main || echo "No changes to push"
